DROP DATABASE IF EXISTS testspring2;
CREATE DATABASE testspring2;

USE testspring2;

CREATE TABLE PRODUIT (
	CODE INT AUTO_INCREMENT NOT NULL,
	DESCRIPTION VARCHAR(255),
	PRIX DOUBLE NOT NULL,
	PRIMARY KEY (CODE)
);

INSERT INTO PRODUIT(DESCRIPTION, PRIX) VALUES
("Produit 1", 1200),
("Produit 2", 2500),
("Produit 3", 3500),
("Produit 4", 4500);


CREATE TABLE ROLES (
	ROLE VARCHAR(50) NOT NULL,
	PRIMARY KEY (ROLE)
);

INSERT INTO ROLES VALUES
("ADMIN"),
("USER");

CREATE TABLE USERS (
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	ACTIVE TINYINT(1) NOT NULL,
	PRIMARY KEY (USERNAME)
);

INSERT INTO USERS VALUES
("admin", "$2a$10$48rHV0wVUbA6mJOgeexVn.olPtKxbtarlQDA98j5Pf6e3a5cKjKpC", 1),
("user", "$2a$10$48rHV0wVUbA6mJOgeexVn.olPtKxbtarlQDA98j5Pf6e3a5cKjKpC", 1),

CREATE TABLE USERS_ROLES (
	USERNAME VARCHAR(50) NOT NULL,
	ROLE VARCHAR(50) NOT NULL,
	PRIMARY KEY (USERNAME, ROLE)
);

INSERT INTO USERS_ROLES VALUES
("admin", "ADMIN"),
("admin", "USER"),
("user", "USER");